version: '3'

services:
  root-graphql:
    build:
      context: .
    image: root-graphql
    # image: localhost:5000/root-graphql
    ports:
      - "3007:3007"
    env_file: .env
    restart: always